### ISSUE TITLE
Partial<QueryString> and string have no overlap

### ISSUE THREAD

**Issue by urecha** [vlvtin/vlquery#21]
Hi there. Still enjoying this ORM, nice that you keep updating.

Using v5.3.0 in a new project, I get a compilation error in here:
```ts
async getByName(name: string): Promise<AppUser | undefined> {
    return await this.dbSet.where(u => u.username == name).first();
}
```
`This condition (u.username == name) will always return 'false' since the types 'Partial<QueryString>' and 'string' have no overlap.`

In another project, where I'm using v4.6.0, that exact line (on a different set, but with the same types) works fine: 
```ts
async getByName(name: string): Promise<Category | undefined> {
    return this.dbSet.where(cat => cat.name == name).first();
}
```

Using `.ValueOf()` on the QueryString gets rid of the compilation error..
Do we **have to** use `QueryString.valueOf()` nowadays or is this a different error?

**Comment by levvij** [comment]
Try updating vlserver to the latest version (v4.4.9), this might fix this issue. 

I have had the same problem before, but I can't find the project anymore.

Thank u for using vlquery🥺

**Comment by levvij** [comment]
The latest version of `vlserver` uses peer dependencies. Upgrade to the latest version (`npm install vlserver@latest`) and the issues should be resolved!

**Comment by urecha** [comment]
Sorry for the late response. Didn't get around to actually trying out the functionality that uses this for quite some time.  

Now, I have "hotfixed" it using `.valueOf()`, while the original error still persists.  

I had tried updating `vlserver` once, without success. Thing is, I'm not explicitly using the `vlserver`  library and as far as I can tell from reading the `package-lock.json`, nor does `vlquery` use it as a dependency.. so I don't see how this would help?

Since the workaround with `valueOf()` worked and my project is terminated, this issue can be closed from my point of view.
